### ISSUE TITLE
Magento Price Rules not carried over correctly to module

### ISSUE THREAD

**Issue by olzen90** [clerkio/clerk-magento#33]
When Price Rules are used in Magento, the module calculates them wrongly, and ends up subtracting the price-rule twice.

Cannot reproduce in our magento.clerk.io setup, but it happens for many customers.

A possible fix is the following:

Open the file
_app -> code -> community -> Clerk -> Clerk -> Model -> Catalog -> productbase.php_

Find the following code starting at line 72:

```
$price = $this->getPrice();
 if ($includeDiscounts) {
     $price = Mage::getModel('catalogrule/rule')
             ->calcProductPriceRule($this, $this->getFinalPrice());
     if (!isset($price)) {
             $price = $this->getFinalPrice();
     }
 }
```

Replace it with the following code:

```
$price = $this->getPrice();
if ($includeDiscounts) {
        $price = Mage::getModel('catalogrule/rule')
        ->calcProductPriceRule($this, $this->getPrice());
        if ($price != $this->getFinalPrice()) {$price = $this->getFinalPrice();}
        if (!isset($price)) {
                $price = $this->getFinalPrice();
        }
}
```

This effectively check if its the right FinalPrice we are using and if not, will set it accordingly.

**Comment by RBech** [comment]
@olzen90 Wouldn't your proposed fix be the same as:
```
$price = $this->getPrice();
if ($includeDiscounts) {
        $price = $this->getFinalPrice();
}
```

Anyway, this would probably not give you the expected behavior, when testing a 100dkk product affected by a 50% price rule with the current code I get the following in clerk

| Field | Type | Value |
| --- | --- | --- |
| discount_percent | number | -49 |
| price | number | 100 |
| price_final_excl_tax | number | 50 |
| price_final_incl_tax | number | 54.125 |
| price_retail_excl_tax | number | 100 |
| price_retail_incl_tax | number | 108.25 |

What would be the expected values when this is fixed?

**Comment by olzen90** [comment]
Hi Rasmus.

As far as I can see the above results look correct, considering the product has a price of 100dkk before taxes. 

The only attribute I can see is wrong is discount_percent, which should of course be 50. 

So the expected values would be:

| Field | Type | Value |
| --- | --- | --- |
| discount_percent | number | 50 |
| price | number | 100 |
| price_final_excl_tax | number | 50 |
| price_final_incl_tax | number | 54.125 |
| price_retail_excl_tax | number | 100 |
| price_retail_incl_tax | number | 108.25 |
