### ISSUE TITLE
Empty attributes in multiselect for Faceted Search

### ISSUE THREAD

**Issue by olivierognn** [clerkio/clerk-magento#92]
![Schermata 2022-10-21 alle 17 31 52](https://user-images.githubusercontent.com/1189457/197233519-7f6e13df-dcec-495a-b31f-fa411c016f60.png)
As you can see I can't select any attributes from Faceted Search after module installed

I Have attributes enabled to be displayed in layer navigation on my Magento 1.9.4.5

**Comment by olivierognn** [comment]
I just tried to install the module on a Magento ver. 1.9.4.5 vanilla environment, I get the same error.

**Comment by FoulBachelor** [comment]
Hi Olivie,

This was happening due to a change in our of our API endpoints. 

https://docs.clerk.io/reference/product-facets

The endpoint would give all unique attribute keys if no attributes or id's were specified. The behaviour was temporarily removed with another optimization, but has been reverted.
